### PR TITLE
Support font files as well as font names for the --font flag.

### PR DESCRIPTION
**Pull request by ehmatthes**
This PR adds support for font files as well as named fonts. Now both of these commands work:

```sh
$ git-sim log --font='Courier New'
$ git-sim log --font='/full/path/to/font_file.ttf'
```

The motivation for this is to address cross-platform testing inconsistencies. There are likely very few end users who would want to run git-sim against a local font file, although as I write that out I start to see use cases. git-sim is quite scriptable, so I could see someone writing a script to generate a series of images or animations, and bundling a font file in order to generate consistent output across different systems.

There are some things to consider before merging this:
- This requires the `fonttools` package, used in \_\_main\_\_.py to pull the name of the font from the font file. I did not add this requirement to pyproject.toml.
- I wasn't exactly sure where to put the function `get_font_name()`. It's currently in \_\_main\_\_.py. 
- I also wasn't sure exactly where to put the code that processes the font argument. I put it in \_\_main\_\_.py, because that's where most other settings seem to be finalized.
- There's a bit of naming difficulty around how the word `font` is used. It can be a path, it can be a named font, it can be a kind of font. I didn't want to mess with any existing usage, so I made a new setting called `font_context`. This is set in \_\_main\_\_.py as either a call to `m.register_font()`, or as a null context. This makes a nice clean change to commands.py, where the call to `_handle_animations()` is either run in a context that has access to the local font file, or a null context where all behavior is as it was before this PR. There's no need to change any of the individual command files. I was not sure exactly what type to assign to `font_context`; I chose `bool` because I don't think `register_font()` [returns anything](https://github.com/ManimCommunity/manim/blob/v0.5.0/manim/mobject/svg/text_mobject.py#L1436). It works, but maybe there's a more precise type for it?
- `get_cmd_parts()` in e2e_tests/utils.py needed a bit of reworking, because `git-sim` is now in the command itself and in the path to the font file. I added a diagnostic print call to show the full test command. You can copy this command, cd to the sample repo, and run this command to see all the output a user would see when running the command. This is really helpful when troubleshooting the test suite itself, and failed tests.
- I chose a [small, open font](https://github.com/bluescan/proggyfonts/blob/master/ProggyOriginal/ProggyClean.ttf) to use for the demo of testing with a local font file. It's rather ugly; I kept it in here for the initial PR because it was helpful to use a font that was visibly very different both from Courier New, and from the default font my system uses when the requested font fails. I think it will be helpful to anyone who reviews this PR as well. When this is merged, it might be good to choose an open font that looks more like the output you're used to.
- I had to replace all the existing reference files. I ran the tests and they all failed as expected. I went into the sample repo and copied all 18 output files, and pasted them into a folder in a git-sim_support/ directory. I then wrote a small script that renames all of those files to remove the timestamps from the file names. I'll share that script; it makes it quick and easy to update all the reference files when you change git-sim in a way that affects all visual output.
- I tested this on Windows. I had to rebuild my environment there. When I installed git-sim, the tests failed because git-dummy did not get placed on the path. I rebuilt the env by installing git-dummy and then git-sim, and things worked again. I'm not sure what caused that.
- I generated the reference files on macOS, and on Windows the highest pixel diff was 0.00532. I think we can probably drop the threshold to 0.0075 again, but I'd want to know that things are working on your system, and on Linux before doing that. Side note, I saw that opencv is a dependency of this project, so there might be a cleaner way to compare images at some point. But that would only affect `compare_images()`, and it wouldn't do anything to address cross-platform issues caused by different fonts.

I doubt this is ready to merge as is, although the remaining work should be a matter of refinement. I think it's worth making the test output consistent if you want the test suite to be useful.

### CODE REVIEW

**Comment by initialcommit-io** [comment]
This looks really great.  Looks like you were spot on with making a self-contained test font a requirement for consistent test results across OS's.  This PR should make consistent testing of git-sim a lot more reliable, and add a handy option for general users if they want to specify a custom font file.

I cloned your branch and did a quick test on my end - it worked on my system.  I did have to manually install fonttools, so I will add that into the `pyproject.toml` deps on my end.  Like you mentioned I'll likely find another font to use as the test font, but like you said the one you used was easy to verify :D.

I'm going to merge this.  Will follow up with results and if any issues in #55 .  But I think this should put us in a pretty stable place.

Oh and PS it would be great to get that script you mentioned for overhauling the reference files.  Feel free to add that into #55 as well.

And thanks again!

**Comment by ehmatthes** [comment]
I'm glad you found this helpful. If you want, it might be a good time to close #55 and open a fresh issue called something like "Refine test suite". There are a few things that we can do to button this work up. For example it would be good to have one test use a named font, and just assert that an image file is generated. I broke support for named fonts at one point, and all tests would have passed at that point. I'm happy to open that issue if you want, with the goal of it not staying open too long.

I'm also happy to validate the Contributing guidelines on some fresh VMs. I'd like to sort out the Windows setup which was inconsistent the one time I tried it yesterday.

**Comment by initialcommit-io** [comment]
@ehmatthes Both of those things sound awesome.  Please go ahead and open up that issue then I'll close #55. I'm curious about the Windows thing you ran into.  Let me know if you're able to reproduce anything on that front.

There is some other refinement to the test suite that I want to do as well, which we could handle in the same issue (but I plan to do the dev for).

Specifically I wanted to update the commands that take files as input, like `add`, `rm`, etc to _actually_ take input in the tests.  To keep things simple for the first iteration I just popped in those commands with no files at all.  I think this will involve updates to git-dummy to generate repos with untracked files, working directory mods, staged files, etc in order to simulate those scenarios.

**Comment by ehmatthes** [comment]
Okay, I opened #99.

> Specifically I wanted to update the commands that take files as input, like add, rm, etc to actually take input in the tests. To keep things simple for the first iteration I just popped in those commands with no files at all. I think this will involve updates to git-dummy to generate repos with untracked files, working directory mods, staged files, etc in order to simulate those scenarios.

I don't know if that's worthwhile right now. I love testing, but one thing to watch out for is spending too much time building out the test suite. We're all told to aim for 100% coverage, and expanding a functioning test suite feels really good and productive. But it's work that's entirely invisible to end users.

I'm a big fan of "good enough" for testing, *especially* for solo projects and projects with small dev teams. Once you've got a functioning test suite in place, it's really good to recognize when it's likely good enough to catch any regressions. At that point, go back to the main development work and only add tests when you add new features to the project, and when people report bugs that aren't caught by current tests.

That said, I'm not quite sure what different output or behavior you're testing for by taking input in the tests. If it's a brittle behavior you're testing, maybe that is worthwhile to test for at the moment.

**Comment by ehmatthes** [comment]
> Oh and PS it would be great to get that script you mentioned for overhauling the reference files.

I dumped that [here](https://github.com/ehmatthes/git-sim/issues/5#issuecomment-1638500258) for now. I'll reimplement this as a pytest flag, so we can run `pytest --rewrite-reference-files`.

**Pull request merged**
