### PR TITLE
code cleanups for python 3+

### PR DESCRIPTION
**Pull request by marksmayo**
- cleaned up imports
 - added 3, 3.5, 3.6+ trailing commas
- tidied whitespace
 - formatted with black

### CODE REVIEW

**Comment by paketb0te** [comment]
+1 for using black for formatting

**Comment by initialcommit-io** [comment]
Hi @marksmayo,

Thanks for this - I hadn't used black before and @paketb0te suggested we used it in a different issue they opened.  I just looked into it and I think we should go for it.

But I've made some conflicting code changes since you submitted this PR.  Can you pull down the updates and run your formatting again, and submit a new PR?

I'll merge that and then we can use black going forward when committing new code.

**Comment by paketb0te** [comment]
-> See my [Comment](https://github.com/initialcommit-com/git-sim/issues/23#issuecomment-1406127194) in #23

**Comment by initialcommit-io** [comment]
Hi @marksmayo,

I took care of the formatting with black and committed.

If you'd like you can clean up the imports and add the trailing commas in a new PR. Not sure if the whitespace updates still apply after the reformatting with black has been done.

**Pull request closed without merging**
